{
 "title": "AdPulse++ Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "campaign_id",
    "label": "Campaign",
    "query": "SELECT DISTINCT campaign_id FROM ad_events ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Device mix ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "adpulse",
     "rawSql": "SELECT\n  metadata->>'device' AS metric,\n  COUNT(*)            AS value\nFROM ad_events\nWHERE $__timeFilter(ts)\n  AND campaign_id ~* '^(?:${campaign_id:regex})$'\nGROUP BY 1\nORDER BY 2 DESC;\n"
    }
   ]
  },
  {
   "title": "Events by type / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', ts) AS time,\n  event_type               AS metric,\n  COUNT(*)                 AS value\nFROM ad_events\nWHERE $__timeFilter(ts)\n  AND campaign_id ~* '^(?:${campaign_id:regex})$'\nGROUP BY 1,2\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Geo breakdown / min (stacked time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "adpulse",
     "rawSql": "SELECT\n  date_trunc('minute', ts) AS \"time\",\n  metadata->>'geo'         AS \"metric\",\n  COUNT(*)::double precision AS \"value\"\nFROM ad_events\nWHERE $__timeFilter(ts)\n  AND campaign_id ~* '^(?:${campaign_id:regex})$'\nGROUP BY 1,2\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "CTR (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (SUM(CASE WHEN event_type='click' THEN 1 END)::float\n        / NULLIF(SUM(CASE WHEN event_type='impression' THEN 1 END),0)) * 100 AS value\nFROM ad_events\nWHERE $__timeFilter(ts) AND campaign_id ~* '^(?:${campaign_id:regex})$';\n"
    }
   ]
  },
  {
   "title": "CVR (%)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (SUM(CASE WHEN event_type='conversion' THEN 1 END)::float\n        / NULLIF(SUM(CASE WHEN event_type='click' THEN 1 END),0)) * 100 AS value\nFROM ad_events\nWHERE $__timeFilter(ts) AND campaign_id ~* '^(?:${campaign_id:regex})$';\n"
    }
   ]
  },
  {
   "title": "ROI (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ((SUM(revenue) - SUM(cost)) / NULLIF(SUM(cost),0)) * 100 AS value\nFROM ad_events\nWHERE $__timeFilter(ts) AND campaign_id ~* '^(?:${campaign_id:regex})$';\n"
    }
   ]
  },
  {
   "title": "Events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', ts) AS time,\n  COUNT(*) / 60.0          AS value\nFROM ad_events\nWHERE $__timeFilter(ts)\n  AND campaign_id ~* '^(?:${campaign_id:regex})$'\nGROUP BY 1\nORDER BY 1;\n\n\n\n"
    }
   ]
  },
  {
   "title": "Cost vs Revenue / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', ts) AS time, 'cost' AS metric, COALESCE(SUM(cost),0) AS value\nFROM ad_events\nWHERE $__timeFilter(ts) AND campaign_id ~* '^(?:${campaign_id:regex})$'\nGROUP BY 1\nUNION ALL\nSELECT date_trunc('minute', ts), 'revenue', COALESCE(SUM(revenue),0)\nFROM ad_events\nWHERE $__timeFilter(ts) AND campaign_id ~* '^(?:${campaign_id:regex})$'\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  }
 ]
}