
name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest ruff
      - name: Lint
        working-directory: backend
        run: ruff check app
      - name: Tests
        working-directory: backend
        run: pytest -q
      - name: Build Docker
        working-directory: backend
        run: docker build -t adpulsepp:ci .
